### ISSUE TITLE
Add additional Vector data for classification

### ISSUE THREAD

**Issue by ratnanil** [sunwell-foss/sonnenland#11]
- [x] Ski Resorts
- [x]  Dams (must be clarified with Annelen) → requires a different radiation calculation (2x no annual or winter optimal)
- [x]  Avalanche defence structures (must be clarified with Annelen)  → requires a different radiation calculation (2x no annual or winter optimal)

**Comment by ratnanil** [comment]
How far are you on this, @vsharma-next?

**Comment by vsharma-next** [comment]
I am inclined to drop all these criteria for now.
