### ISSUE TITLE
Raster Projection / Resolution?

### ISSUE THREAD

**Issue by ratnanil** [sunwell-foss/sonnenland#3]
Hey @vsharma-next, [here](https://sunwell-switzerland.notion.site/Collaboration-with-Nils-5fcb9e5334e3412d82a1caed6ed672c5) you state:

> Raster files (Geotiffs) @ 20 m resolution with EPSG: 2056, float32

But ogrinfo shows me this:

```
$ gdalinfo data/Dataset_SONNENLAND/Radiation/tilt_30_summer.tif | grep PROJCRS
PROJCRS["ETRS89_ETRS_LAEA",
```

**Comment by ratnanil** [comment]
Also

```
$ gdalinfo data/Dataset_SONNENLAND/Radiation/tilt_30_summer.tif | grep Pixel  
Pixel Size = (25.000000000000000,-25.000000000000000)
```

**Comment by vsharma-next** [comment]
You are quite right @ratnanil . The projections and resolutions are indeed what gdal is telling out. Furthermore, that is the projection in which I intended to give you the date. I made a mistake in my description on the webpage.
