### ISSUE TITLE
Raster value units?

### ISSUE THREAD

**Issue by ratnanil** [sunwell-foss/sonnenland#4]
Hey @vsharma-next, [here](https://sunwell-switzerland.notion.site/Collaboration-with-Nils-5fcb9e5334e3412d82a1caed6ed672c5) you state:

> Sample radiation datasets for a single tilt (30 degrees) for summer and winter are provided.

What is the unit of the values? On the phone you mentioned Wh/m<sup>2</sup>, on notion the other datasets supposedly will be in KWh/m<sup>2</sup>

**Comment by vsharma-next** [comment]
It is in Wh / m2.
