### ISSUE TITLE
Lakes on Swiss borders

### ISSUE THREAD

**Issue by ratnanil** [sunwell-foss/sonnenland#5]
Hey @vsharma-next, [here](https://sunwell-switzerland.notion.site/Collaboration-with-Nils-5fcb9e5334e3412d82a1caed6ed672c5) you state:

> Standing’ Water Bodies -ie. no rivers 

The three largest lakes in Switzerland, Bodensee, Lac Léman and Lago Maggiore are only partially in Switzerland. The dataset `OBJEKTART_Stehende Gewaesser.shp` contain the whole lakes. How should I deal with the raster values in these lakes? 

- include the whole lake?
- include only part of the lake that is within the border?

![image](https://user-images.githubusercontent.com/12532091/236581770-dec18e6e-c4d0-4f37-81bd-e8577aa82a32.png)
![image](https://user-images.githubusercontent.com/12532091/236581793-dfb9e15b-4fc3-49e2-acaa-2ffe4c588ecb.png)
![image](https://user-images.githubusercontent.com/12532091/236581812-b0cb4a6e-756e-4bde-8711-b3bb99c3bd97.png)

**Comment by vsharma-next** [comment]
Only those within the swiss national boundaries. As a suggestion you should use the dataset found [here](https://www.swisstopo.admin.ch/de/geodata/landscape/boundaries3d.html)
