### ISSUE TITLE
Many very small standing waters

### ISSUE THREAD

**Issue by ratnanil** [sunwell-foss/sonnenland#6]
I've notice that in the standing waters dataset, a vast majority of all features are *very* small lakes. 

For example, the following lake has a surface area of 24 a (2'400 m<sup>2</sup>). The pond is located [here](https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&E=2721110&N=1275044&zoom=10&crosshair=marker).

![image](https://user-images.githubusercontent.com/12532091/236583695-94ca01f3-4d0e-4f59-a40c-1a1b2df0bb10.png)

The distribution shows, that a vast majority of all standing waters have a surface area of less than 100 a (~100 x 100 m). Should we include all these little lakes in our analysis?

![image](https://user-images.githubusercontent.com/12532091/236583649-07400161-401a-4c25-a03a-4f22a85e9138.png)

**Comment by vsharma-next** [comment]
Good Point @ratnanil 

-> Lets limit the lake sizes to **those > 10,000 square meters**. That would give us a minimum of 1 MW ( potentially more ) installation.

**Comment by ratnanil** [comment]
I raised this issue originally, thinking that if the size of the raster size is not in relation to the size of the lakes, our results would be completely off. However, since we only take the mean of the raster values and the effective size provided by the vector data, the estimates can be considered accurate. Let's discuss this tomorrow.
